# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: api_walker.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61pi_walker.proto\x12\napi_walker\"!\n\x0eRequestMessage\x12\x0f\n\x07message\x18\x01 \x01(\t\"\x1f\n\x0cReplyMessage\x12\x0f\n\x07message\x18\x01 \x01(\t2Q\n\tApiWalker\x12\x44\n\nGetMessage\x12\x1a.api_walker.RequestMessage\x1a\x18.api_walker.ReplyMessage\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api_walker_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_REQUESTMESSAGE']._serialized_start=32
  _globals['_REQUESTMESSAGE']._serialized_end=65
  _globals['_REPLYMESSAGE']._serialized_start=67
  _globals['_REPLYMESSAGE']._serialized_end=98
  _globals['_APIWALKER']._serialized_start=100
  _globals['_APIWALKER']._serialized_end=181
# @@protoc_insertion_point(module_scope)
